In [ ]:
import csv
import pandas as pd
import random
import itertools
import numpy as np
from google.colab import drive
import re

## Guide
### Instructions
1) Dormspam the Tuesday a week prior to the week of the event.
2) Close reservation form Sunday at midnight.
3) Add all kerbs in current reservation form to the "tracking.csv" file. Be sure to indicate the current event.
4) Add all kerbs that were accepted in the last event to the "accepted.csv" file. Be sure to indicate what the last event was.
5) Import a csv file of the reservations for the current event. Rename the relevant column names to "seats", "names", "kerbs", and "allergies".
6) Rename the file and update the variable in the code block below. For example, if I renamed the file to "mince_dec.csv", I would update the file variable to "mince_dec.csv".
7) Run all code blocks.
8) Manually check the selected guests to ensure that they don't have any relevant dietary restrictions.

### Rules
* The weight of a group of people is equivalent to the average of all individual weights in the group
* Once someone receives a spot in a Pop up, their weight resets to 0

### Key
1) **bang**: Flung out of Space
2) **armenia**: Armenia
3) **fall**: Fall in New England
4) **art**: Night at the Art Gallery

### Update these variables!

In [ ]:
events = [
    "bang", "armenia", "fall", "art",
    "india", "datamatch", "picnic",
    "tea", "alice", "earth",
    "lny", "japan", "italy",
    "garden", "supper", "brazil",
    "ghibli", "swotw", "africa",
    "untitled", "ayuy", "entropy"
]
events = {e: i for i, e in enumerate(events)}

In [ ]:
drive.mount('/content/drive', force_remount=True) #or however works best for u

Mounted at /content/drive

### Create log.csv
The log.csv file records the number of times someone has registered for a MINCE Pop up, how many MINCE Pop ups they've attended, the last event they attended, and how many lottery tickets they currently hold.

In [ ]:
class Guest:
    def __init__(self, kerb):
        self.kerb = kerb
        self.count = 0
        self.accepted = 0
        self.current_weight = 0
        self.last_attended = None



df_tracking = pd.read_csv('/content/drive/My Drive/[MINCE] General/master documents/lottery/tracking.csv')
df_accepted = pd.read_csv('/content/drive/My Drive/[MINCE] General/master documents/lottery/accepted.csv')

log_tracking = {}

def parse_kerbs_str(kerbs_str):
  kerbs = re.split('[;,]', kerbs_str)

  out = []
  for kerb in kerbs:
      kerb = kerb.lower().strip()
      if not kerb:
        continue
      if not (kerb.endswith('@mit.edu') or '@' in kerb) :
          kerb += '@mit.edu'
      out.append(kerb)
  return out

def extract_kerbs(df):
    for k, event in zip(df['kerb'], df['event']):
      if type(k) != str:
          continue
      kerbs = parse_kerbs_str(k)
      for kerb in kerbs:
          if kerb not in log_tracking:
            log_tracking[kerb] = Guest(kerb)
          yield kerb, event


# first we look at who was accepted before
for kerb, event in extract_kerbs(df_accepted):
    log_tracking[kerb].accepted += 1
    log_tracking[kerb].last_attended = event
    print(kerb)

for kerb, event in extract_kerbs(df_tracking):
    log_tracking[kerb].count += 1
    log_tracking[kerb].current_weight += 1
    if log_tracking[kerb].last_attended == event: #Reset for last attended
        log_tracking[kerb].current_weight = 0
    print(kerb)

guests = []
for kerb, guest in log_tracking.items():
  weight = guest.current_weight
  guests.append([kerb, guest.count, guest.accepted, weight, guest.last_attended])

df_log = pd.DataFrame(guests, columns=["kerbs", "counts", "accepted", "weight", "last attended"])
df_log.to_csv('log.csv')

iliu@mit.edu
jszhu@mit.edu
sabchen@mit.edu
louisea@mit.edu
eyosias@mit.edu
tafeyan@gmail.com
beverlym@mit.edu
janicey@mit.edu
maxfan@mit.edu
kjulca@mit.edu
dogbe@mit.edu
azf@mit.edu
moralejo@mit.edu
laiwachu@mit.edu
handales@mit.edu
timberc@mit.edu
evag@mit.edu
katwli@mit.edu
katwli@mit.edu
yazana@mit.edu
mgeo@mit.edu
wendyz@mit.edu
iliao@mit.edu
abelyan@mit.edu
grigt@mit.edu
mshafim@mit.edu
jcahaly@mit.edu
mtang17@mit.edu
ptimil@mit.edu
zabroves@mit.edu
mnatalie@mit.edu
armen@sloan.mit.edu
ramirjos@mit.edu
diao@mit.edu
emmachen@mit.edu
jacobrod@mit.edu
nyouyang@mit.edu
mzetina@mit.edu
miglesia@mit.edu
yanswu@mit.edu
spruce@mit.edu
greerj@mit.edu
teejay@mit.edu
ayoub@mit.edu
jocelin@mit.edu
curtiss@mit.edu
jmfortt@mit.edu
alisonw@mit.edu
smthom@mit.edu
rya@mit.edu
emilywg@mit.edu
chrswang@mit.edu
mqwang@mit.edu
michli@mit.edu
pronina@mit.edu
lcui@mit.edu
solcu483@mit.edu
fmn@mit.edu
gminnout@mit.edu
cindyxie@mit.edu
claraxu@mit.edu
wangcx@mit.edu
chxchen@mit.edu
hgazdus@mit.edu
chriswu@mit.edu
rona@mit.edu
maanasak@mit.edu
aliciaz@mit.edu
arushim@mit.edu
lynnye27@mit.edu
nirvan@mit.edu
lusophie@mit.edu
ckokesh@mit.edu
jacklin8@mit.edu
maguiar@mit.edu
sadhana@mit.edu
jeslam@mit.edu
auds@mit.edu
alinasar@mit.edu
shreya46@mit.edu
rlizarde@mit.edu
jbsera@mit.edu
audcui@mit.edu
wszeto@mit.edu
nvenkat@mit.edu
emilywg@mit.edu
ikrosado@mit.edu
kcard@mit.edu
ayodeji@mit.edu
selenal@mit.edu
shriyamr@mit.edu
puria@mit.edu
eranade@mit.edu
apranav@mit.edu
sncn@mit.edu
rmoswane@mit.edu
klpan@mit.edu
ayjchen@mit.edu
asu@mit.edu
greerj@mit.edu
ruthluvu@mit.edu
jennyz@mit.edu
ctrlz@mit.edu
gkim17@mit.edu
emfang@mit.edu
liviasyz@mit.edu
jessding@mit.edu
mnocito@mit.edu
ebazakas@mit.edu
mayajyo@mit.edu
wangcx@mit.edu
mzw@mit.edu
fukumoto@mit.edu
eliu24@mit.edu
michesba@mit.edu
emilych@mit.edu
camim@mit.edu
raytran@mit.edu
fjiahai@mit.edu
mniwheat@mit.edu
sgabbita@mit.edu
cfalor@mit.edu
celinaz@mit.edu
mariali@mit.edu
timmyd@mit.edu
gting@mit.edu
xieyi@mit.edu
rupertli@mit.edu
luclaire@mit.edu
brrich@mit.edu
kaivu@mit.edu
lyuyuan@mit.edu
mtopalli@mit.edu
zdhunsuc@mit.edu
katieliu@mit.edu
kemily@mit.edu
julianag@mit.edu
joshlee5@mit.edu
dxhong@mit.edu
akuka@mit.edu
sogreen@mit.edu
ssalwan@mit.edu
kjulca@mit.edu
whuang03@mit.edu
jcai1@mit.edu
jeyoon@mit.edu
shashvat@mit.edu
derchen@mit.edu
fle@mit.edu
pizzol@mit.edu
kyralynn@mit.edu
jbsera@mit.edu
helenkw@mit.edu
tinachen@mit.edu
deraaij@mit.edu
ljelu@mit.edu
notadib@mit.edu
sschao@mit.edu
mvemuri@mit.edu
sarahlu@mit.edu
vishruti@mit.edu
neosha@mit.edu
justshan@mit.edu
tinahh@mit.edu
andresb@mit.edu
sflorin@mit.edu
mtxiang@mit.edu
serenc@mit.edu
isaq@mit.edu
ajiao@mit.edu
jlmeng@mit.edu
jjx@mit.edu
henryrh@mit.edu
jianmc@mit.edu
kellh219@mit.edu
alin45@mit.edu
jnwang@mit.edu
jzli@mit.edu
carlguo@mit.edu
redzheng@mit.edu
sunsh16e@mit.edu
bting@mit.edu
pedrob@mit.edu
alysse pusey@mit.edu
tasnim@mit.edu
emanant@mit.edu
kgusty@mit.edu
danahua@mit.edu
n10nyiam@mit.edu
opalinav@mit.edu
andreags@mit.edu
kanotung@mit.edu
sabchen@mit.edu
kamsi@mit.edu
joym@mit.edu
ckf@mit.edu
leelaf@mit.edu
sienna@bu.edu
sangitavv@gmail.com
ssalwan@mit.edu
emily272@mit.edu
sasne@mit.edu
fey@mit.edu
sabpdo@mit.edu
pamadeo@mit.edu
mehek@mit.edu
yanswu@mit.edu
mshafim@mit.edu
natdean@mit.edu
siyi@mit.edu
spar@mit.edu
tatianav@mit.edu
mstok@mit.edu
nsthakur@mit.edu
eves@mit.edu
ksanj@mit.edu
say@mit.edu
cmao22@mit.edu
nebus12@mit.edu
haydnl@mit.edu
srinaray@mit.edu
elainelw@mit.edu
pbalaji@mit.edu
samayg@mit.edu
lepei@mit.edu
cassye@mit.edu
gracesun@mit.edu
cduong@mit.edu
emli@mit.edu
jbenke@mit.edu
tnh8210@mit.edu
yijuny@mit.edu
livlee@mit.edu
ejiang@mit.edu
michmo@mit.edu
ishitab@mit.edu
janetq@mit.edu
sophia_s@mit.edu
mkrystal@mit.edu
annaliu@mit.edu
jyotsnan@mit.edu
emva@mit.edu
asu@mit.edu
greerj@mit.edu
peihua@mit.edu
vickyl@mit.edu
rumilee@mit.edu
matildas@mit.edu
katdou@mit.edu
cateli@mit.edu
whuang03@mit.edu
iankoe@mit.edu
akleang@mit.edu
pyleang@mit.edu
kiera@mit.edu
amacavoy@mit.edu
sabchen@mit.edu
ankaa@mit.edu
sophi120@mit.edu
iliao@mit.edu
gracezj@mit.edu
ahulver@mit.edu
emira@mit.edu
chuang26@mit.edu
pxliu@mit.edu
timmyd@mit.edu
zef@mit.edu
califyn@mit.edu
sruthik@mit.edu
kduan@mit.edu
pamadeo@mit.edu
ctu@mit.edu
hannahkm@mit.edu
jmlaw@mit.edu
tms255@mit.edu
leik@mit.edu
jhuang25@mit.edu
osampson@mit.edu
huangn@mit.edu
tinachen@mit.edu
echo314@mit.edu
jkim25@mit.edu
cadenm@mit.edu
pisinger@mit.edu
cbush@mit.edu
claraxu@mit.edu
geshu@mit.edu
muhuaxu@mit.edu
whuang03@mit.edu
jcai1@mit.edu
ruthluvu@mit.edu
byliu@mit.edu
amys0930@mit.edu
azang@mit.edu
froit@mit.edu
qqouyang@mit.edu
kylat777@mit.edu
danielvi@mit.edu
seanjli@mit.edu
amzhao@mit.edu
derrick8@mit.edu
leonfan@mit.edu
jacksonz@mit.edu
vittalt@mit.edu
kxie22@mit.edu
ashleyz@mit.edu
ckf@mit.edu
chriswu@mit.edu
zipeitan@mit.edu
jessw@mit.edu
isabelsp@mit.edu
jjx@mit.edu
sarahyw@mit.edu
chrisscp@mit.edu
the0@mit.edu
yujenny@mit.edu
steph@mit.edu
ksiyoung@mit.edu
diptasri@mit.edu
vickyz@mit.edu
chuang26@mit.edu
ejiang@mit.edu
wangsj@mit.edu
mxdu@mit.edu
paurm8@mit.edu
ebazakas@mit.edu
danahua@mit.edu
pedrob@mit.edu
jason_li@mit.edu
sophc@mit.edu
juylee24@mit.edu
lmtorola@mit.edu
msmith26@mit.edu
nattang@mit.edu
fxwang@mit.edu
rebchang@mit.edu
aasahoo@mit.edu
jankah@mit.edu
almogh@mit.edu
mungbean@mit.edu
tswarken@mit.edu
hannahkm@mit.edu
kzhao02@mit.edu
lwl@mit.edu
vymu@mit.edu
jhe2155@mit.edu
laureny@mit.edu
bridgetl@mit.edu
vyuen@mit.edu
korantes@mit.edu
kyaguchi@mit.edu
ylanaxu@mit.edu
raywang4@mit.edu
caseyf@mit.edu
ammel@mit.edu
luciajw@mit.edu
aevum@mit.edu
andyfo@mit.edu
caalvara@mit.edu
dewei@mit.edu
ekaz@mit.edu
julieyu@mit.edu
sphuang@mit.edu
scchung@mit.edu
winixent@mit.edu
fxh@mit.edu
ssferza@mit.edu
rlck@mit.edu
padour@mit.edu
wdmc@mit.edu
ylfl@mit.edu
solam@mit.edu
sjhlee@mit.edu
layla99@mit.edu
abigailt@mit.edu
vkhim@mit.edu
mzheng01@mit.edu
yuecli@mit.edu
anavad@mit.edu
shaylatn@mit.edu
sshong@mit.edu
dais@mit.edu
gracesun@mit.edu
zakzhang@mit.edu
anuc@mit.edu
rgabriel@mit.edu
mycao@mit.edu
amcooper@mit.edu
nabate@mit.edu
txdo@mit.edu
audr3y@mit.edu
jasshone@mit.edu
sarahwei@mit.edu
gracep@mit.edu
joey91@mit.edu
kimliao@mit.edu
mzong@mit.edu
annewang@mit.edu
elizke@mit.edu
shreyar@mit.edu
sjzheng@mit.edu
kellycui@mit.edu
derchen@mit.edu
katguo@mit.edu
emilywg@mit.edu
anushka6@mit.edu
xabackus@mit.edu
adithyab@mit.edu
shreyark@mit.edu
c_myers@mit.edu
linmari4@mit.edu
axlin@mit.edu
cindywei@mit.edu
agrawald@mit.edu
emilyz26@mit.edu
ellieb@mit.edu
shrutsiv@mit.edu
iduran@mit.edu
rduran@mit.edu
argorti@mit.edu
srishtiv@mit.edu
hhicks18@mit.edu
natdean@mit.edu
caseyf@mit.edu
jhoule@mit.edu
duesselc@mit.edu
timberc@mit.edu
mtala@mit.edu
jcai1@mit.edu
myxwang@mit.edu
ebhat@mit.edu
feli@mit.edu
wuthomas@mit.edu
kpanebia@mit.edu
wendyz@mit.edu
livlee@mit.edu
eahuactz@mit.edu
map1147@mit.edu
nmquan@mit.edu
kemily@mit.edu
fdshoff@mit.edu
akim05@mit.edu
beverlym@mit.edu
carlguo@mit.edu
wendycao@mit.edu
haozh@mit.edu
hail01@mit.edu
hyewona@mit.edu
kimele03@mit.edu
smei8@mit.edu
vrosales@mit.edu
munoz03@mit.edu
mys1@mit.edu
jxhn@mit.edu
cma26@mit.edu
maureenz@mit.edu
elixy@mit.edu
wujl@mit.edu
rhwb@mit.edu
gabimcd@mit.edu
oorlik@mit.edu
mqwang@mit.edu
emilysz@mit.edu
tananya@mit.edu
guib@mit.edu
cfalor@mit.edu
dongchan@mit.edu
bronwynb@mit.edu
elsa2499@mit.edu
beap@mit.edu
cadaanma@mit.edu
asantosf@mit.edu
fionali@mit.edu
ernestog@mit.edu
claire25@mit.edu
annieguo@mit.edu
megan_z@mit.edu
nicoli23@mit.edu
ashlu1@mit.edu
diegos@mit.edu
uliana_m@mit.edu
jy100@wellesley.edu
zhangtin@mit.edu
joshua47@mit.edu
mollym12@mit.edu
cduong@mit.edu
svpom@mit.edu
elisaxia@mit.edu
wendyz@mit.edu
riaverma@mit.edu
angelnuz@mit.edu
vivguo@mit.edu
cmao22@mit.edu
skrem@mit.edu
jyuan24@mit.edu
jennyxz@mit.edu
yaohuili@mit.edu
aimeew@mit.edu
jdurham@mit.edu
tklouie@mit.edu
ryanyang@mit.edu
ayl27@mit.edu
lw0328@mit.edu
gloriazh@mit.edu
teejay@mit.edu
vshir@mit.edu
jjx@mit.edu
froit@mit.edu
abrianna@mit.edu
srishtiv@mit.edu
emilych@mit.edu
juylee24@mit.edu
thule@mit.edu
jnix@mit.edu
glohuang@mit.edu
laraoz@mit.edu
julilian@mit.edu
joyzhuo@mit.edu
mag_zhou@mit.edu
yiqingdu@mit.edu
rpartha@mit.edu
htao@mit.edu
jasshone@mit.edu
syao26@mit.edu
gytian@mit.edu
lianexu@mit.edu
mliang51@mit.edu
ddang@mit.edu
lealan@mit.edu
yongao@mit.edu
yzx@mit.edu
leanntai@mit.edu
henryrh@mit.edu
harryh@mit.edu
kellywu@mit.edu
echen02@mit.edu
renge@mit.edu
maysonet@mit.edu
anaveen@mit.edu
llevy@mit.edu
zaeeshah@mit.edu
alinay@mit.edu
agxu@mit.edu
hzyildiz@mit.edu
tkorkot@mit.edu
myxwang@mit.edu
sameen_a@mit.edu
hagerg57@mit.edu
alexclee@mit.edu
augustyn@mit.edu
ruthluvu@mit.edu
byliu@mit.edu
ckf@mit.edu
laiba410@mit.edu
fedaa@mit.edu
yujenny@mit.edu
katwli@mit.edu
sophiez@mit.edu
cattang@mit.edu
nishabk@mit.edu
careen@mit.edu
katieliu@mit.edu
aliciasc@mit.edu
kzl@mit.edu
betsy124@mit.edu
amacavoy@mit.edu
jmacavoy25@gmail.com
anpuri@mit.edu
srihitha@mit.edu
hclee26@mit.edu
jasonehc@mit.edu
timberc@mit.edu
mtala@mit.edu
emilysz@mit.edu
azhang03@mit.edu
emily272@mit.edu
escott26@mit.edu
tananya@mit.edu
wcrosby@mit.edu
hhussein@mit.edu
joshosi@mit.edu
cd117@wellesley.edu
mpfinlay@mit.edu
ebhat@mit.edu
carlguo@mit.edu
jaynaw@mit.edu
lakshmibaloo@hotmail.com
jameel_saeb@brown.edu
btho@mit.edu
aschwanz@mit.edu
joyren@mit.edu
ansia@mit.edu
alyssabg@mit.edu
pengs14@mit.edu
meddour@mit.edu
hmatusik@mit.edu
arielsie@mit.edu
wwhazell@mit.edu
rvaleria@mit.edu
alliande@mit.edu
cwx@mit.edu
riaverma@mit.edu
manxishi@mit.edu
eqiao@mit.edu
ivanciel@mit.edu
colinzh@mit.edu
durresi@mit.edu
tssarma@mit.edu
li_me@mit.edu
sophielw@mit.edu
akzheng@mit.edu
akshatc@mit.edu
angzhu@mit.edu
nic0les@mit.edu
dyne@mit.edu
hdchung@mit.edu
agxu@mit.edu
larab@mit.edu
ivy.w.shi@gmail.com
vivienh@mit.edu
emilyz26@mit.edu
vcpatino@mit.edu
amannmahajan@college.harvard.edu
ayoub@mit.edu
ruthluvu@mit.edu
byliu@mit.edu
yujenny@mit.edu
katwli@mit.edu
exliu@mit.edu
mkrystal@mit.edu
sophie28@mit.edu
osmond@mit.edu
hagerg57@mit.edu
vaddala7@mit.edu
nattang@mit.edu
michmo@mit.edu
ellei89@mit.edu
curtiss@mit.edu
twbrew@mit.edu
aywu@mit.edu
yaqili@mit.edu
eviezh@mit.edu
sjhlee@mit.edu
eyxiong@mit.edu
aspark7@mit.edu
xabackus@mit.edu
anushka6@mit.edu
liujanet@mit.edu
meliliu@mit.edu
dvprasad@mit.edu
kcshen@mit.edu
ahulver@mit.edu
suahong@mit.edu
xieyi@mit.edu
sying@mit.edu
curtiss@mit.edu
camim@mit.edu
soche@mit.edu
mayajyo@mit.edu
seyunom@bu.edu
mgeo@mit.edu
emilywg@mit.edu
ppxscal@mit.edu
vyyang@mit.edu
bridgetl@mit.edu
fxwang@mit.edu
erinay@mit.edu
rmoswane@mit.edu
luclaire@mit.edu
yanswu@mit.edu
shuacho@mit.edu
pronina@mit.edu
amyzhong@mit.edu
pj_iii@mit.edu
tamatsu@mit.edu
audcui@mit.edu
nyouyang@mit.edu
claire25@mit.edu
miatian@mit.edu
paulihim@mit.edu
benjikan@mit.edu
sncn@mit.edu
miglesia@mit.edu
emmachen@mit.edu
sebagarc@mit.edu
somaiars@mit.edu
emanant@mit.edu
erenshin@mit.edu
hann@mit.edu
warneryd@mit.edu
nelle@mit.edu
cnamuroy@mit.edu
audea@mit.edu
favoured@mit.edu
ckf@mit.edu
mtang17@mit.edu
lucykim@mit.edu
vhs@mit.edu
rumilee@mit.edu
aayushg@mit.edu
gminnout@mit.edu
jacobrod@mit.edu
tasnim@mit.edu
jacobrod@mit.edu
diao@mit.edu
iliu@mit.edu
jocelin@mit.edu
alisonw@mit.edu
beverlym@mit.edu
yujenny@mit.edu
rya@mit.edu
dansl@mit.edu
ianl@mit.edu
azang@mit.edu
moralejo@mit.edu
sestinj@mit.edu
meganwei@mit.edu
gkim17@mit.edu
kristenp@mit.edu
justshan@mit.edu
meganxu@mit.edu
anuc@mit.edu
annasun@mit.edu
huanga@mit.edu
valmg@mit.edu
claraxu@mit.edu
ljain@mit.edu
fmn@mit.edu
guoj1112@mit.edu
lcui@mit.edu
zipeitan@mit.edu
ddelarue@mit.edu
michli@mit.edu
elijahf@mit.edu
fionalin@mit.edu
ccwarn@mit.edu
maximna@mit.edu
helenkw@mit.edu
grendy@mit.edu
kuze@mit.edu
zoels@mit.edu
wangcx@mit.edu
vickywc@mit.edu
luciajw@mit.edu
alexishu@mit.edu
mattsoza@mit.edu
cjx@mit.edu
matthew_@mit.edu
jessding@mit.edu
frankgon@mit.edu
andresb@mit.edu
laiwachu@mit.edu
kaitlim@mit.edu
rloha@mit.edu
cruzss@mit.edu
henryrh@mit.edu
harryh@mit.edu
selenal@mit.edu
bweizer@mit.edu
mulanj@mit.edu
ikrosado@mit.edu
emmashi@mit.edu
carlguo@mit.edu
huangq@mit.edu
philena@mit.edu
kavyaa@mit.edu
mdemeyer@mit.edu
headd902@mit.edu
jhe2155@mit.edu
spruce@mit.edu
mqwang@mit.edu
gting@mit.edu
rld@mit.edu
smthom@mit.edu
amandat@mit.edu
ayoub@mit.edu
maxfan@mit.edu
jlmeng@mit.edu
ckokesh@mit.edu
jnwang@mit.edu
califyn@mit.edu
mindyz@mit.edu
sflorin@mit.edu
katcha22@mit.edu
iliao@mit.edu
hgazdus@mit.edu
jthi@mit.edu
azf@mit.edu
chuang26@mit.edu
caseyf@mit.edu
jmfortt@mit.edu
mniwheat@mit.edu
yujing6@mit.edu
asu@mit.edu
kvfrans@mit.edu
muhuaxu@mit.edu
danielxu@mit.edu
lcarethe@mit.edu
jasonehc@mit.edu
sabchen@mit.edu
ramirjos@mit.edu
emichen@mit.edu
zitongc@mit.edu
katchoi@mit.edu
chrswang@mit.edu
luhtaru@mit.edu
axguo@mit.edu
solcu483@mit.edu
mys1@mit.edu
timberc@mit.edu
greerj@mit.edu
teejay@mit.edu
julia815@mit.edu
cmzheng@mit.edu
katwli@mit.edu
ashleyke@mit.edu
ryanyang@mit.edu
bryanmw@mit.edu
axing@mit.edu
mzetina@mit.edu
meerag@mit.edu
chriswu@mit.edu
ankaa@mit.edu
curtiss@mit.edu
rileyis@mit.edu
beverlym@mit.edu
mindyz@mit.edu
tylon@mit.edu
dogbe@mit.edu
janicey@mit.edu
fjiahai@mit.edu
gting@mit.edu
maggiejl@mit.edu
yiqingdu@mit.edu
nirvan@mit.edu
m2w@mit.edu
span@mit.edu
emwang23@mit.edu
ajroth@mit.edu
iliao@mit.edu
yimingc@mit.edu
audcui@mit.edu
wszeto@mit.edu
duhasyar@mit.edu
sheehant@mit.edu
ccunning@mit.edu
mstok@mit.edu
hannach8@mit.edu
weialex@mit.edu
pennyb@mit.edu
spar@mit.edu
jxiu@mit.edu
ayjchen@mit.edu
klpan@mit.edu
timberc@mit.edu
mtala@mit.edu
kcard@mit.edu
ayodeji@mit.edu
hgazdus@mit.edu
malur@mit.edu
mniwheat@mit.edu
helenkw@mit.edu
nvenkat@mit.edu
michesba@mit.edu
michmo@mit.edu
yujenny@mit.edu
chriswu@mit.edu
jbsera@mit.edu
mariano1@mit.edu
cfalor@mit.edu
scchung@mit.edu
claraxu@mit.edu
ksanj@mit.edu
wangcx@mit.edu
chxchen@mit.edu
jennyz@mit.edu
ctrlz@mit.edu
jocelin@mit.edu
mmsun@mit.edu
gnsmith@mit.edu
alicelam@mit.edu
jhoule@mit.edu
duesselc@mit.edu
kav@mit.edu
rya@mit.edu
aliciaz@mit.edu
arushim@mit.edu
lynnye27@mit.edu
tarushii@mit.edu
azf@mit.edu
tatianav@mit.edu
jlmeng@mit.edu
aqding@mit.edu
eyf@mit.edu
jinger@mit.edu
warneryd@mit.edu
jhe2155@mit.edu
brennane@mit.edu
ramirjos@mit.edu
ruthluvu@mit.edu
amli@mit.edu
songk@mit.edu
puria@mit.edu
eranade@mit.edu
apranav@mit.edu
lusophie@mit.edu
liviasyz@mit.edu
jeslam@mit.edu
auds@mit.edu
alinasar@mit.edu
favoured@mit.edu
asantosf@mit.edu
sadhana@mit.edu
shriyamr@mit.edu
luciajw@mit.edu
cindyxie@mit.edu
rona@mit.edu
maanasak@mit.edu
shreya46@mit.edu
rlizarde@mit.edu
jbsera@mit.edu
agbing@mit.edu
emilymu@mit.edu
bardc@mit.edu
avelez9@mit.edu
mgeo@mit.edu
ebazakas@mit.edu
fduong@mit.edu
emilywg@mit.edu
sogreen@mit.edu
selenal@mit.edu
diao@mit.edu
ckokesh@mit.edu
jacklin8@mit.edu
maguiar@mit.edu
kgusty@mit.edu
alissa02@mit.edu
czha@mit.edu
lianexu@mit.edu
rekish@mit.edu
ikrosado@mit.edu
sncn@mit.edu
jyuan24@mit.edu
ramgus@mit.edu
jessding@mit.edu
janicey@mit.edu
greerj@mit.edu
timberc@mit.edu
mniwheat@mit.edu
jennyz@mit.edu
vickywc@mit.edu
maggiel@mit.edu
ramirjos@mit.edu
iganguly@mit.edu
gytian@mit.edu
kjulca@mit.edu
via@mit.edu
tasnim@mit.edu
ptimil@mit.edu
imhari@mit.edu
ahhh@mit.edu
cattang@mit.edu
jszhu@mit.edu
cfalor@mit.edu
grace201@mit.edu
abelyan@mit.edu
diao@mit.edu
ylanaxu@mit.edu
meaderp@mit.edu
azf@mit.edu
iliu@mit.edu
m2w@mit.edu
nvanwijk@mit.edu
luclaire@mit.edu
anuc@mit.edu
nbasu@mit.edu
lusophie@mit.edu
jlu25@mit.edu
audcui@mit.edu
hgazdus@mit.edu
andresb@mit.edu
iliao@mit.edu
wangcx@mit.edu
xieyi@mit.edu
sflorin@mit.edu
mlchiang@mit.edu
maggiejl@mit.edu
fjiahai@mit.edu
klpan@mit.edu
moralejo@mit.edu
ayjchen@mit.edu
wendyz@mit.edu
mshafim@mit.edu
selenal@mit.edu
jdurham@mit.edu
laiwachu@mit.edu
rudiba@mit.edu
shinghos@mit.edu
yujenny@mit.edu
evag@mit.edu
echadwic@mit.edu
asu@mit.edu
ealiu@mit.edu
cma26@mit.edu
katwli@mit.edu
daniel66@mit.edu
vzxiao@mit.edu
hmsalem@mit.edu
suasn@mit.edu
haimo@mit.edu
yazana@mit.edu
ruthluvu@mit.edu
mteodros@mit.edu
chriswu@mit.edu
zhixingc@mit.edu
gting@mit.edu
fukumoto@mit.edu
sophc@mit.edu
mgeo@mit.edu
aarushim@mit.edu
maxfan@mit.edu
alicelam@mit.edu
gkim17@mit.edu
jcahaly@mit.edu
harryh@mit.edu
henryrh@mit.edu
beverlym@mit.edu
vyuen@mit.edu
louisea@mit.edu
liviasyz@mit.edu
eyosias@mit.edu
songk@mit.edu
avelez9@mit.edu
tinahh@mit.edu
ebazakas@mit.edu
michli@mit.edu
loreta03@mit.edu
iwebb@mit.edu
kellylu@mit.edu
curtiss@mit.edu
mtang17@mit.edu
dogbe@mit.edu
ikrosado@mit.edu
ashley22@mit.edu
handales@mit.edu
sjzheng@mit.edu
amirarav@mit.edu
mnocito@mit.edu
sebaszhu@mit.edu
alexzli@mit.edu
magxyu@mit.edu
claraxu@mit.edu
jbsera@mit.edu
rileyis@mit.edu
carlguo@mit.edu
keqian@mit.edu
sabchen@mit.edu
mwen@mit.edu
mnatalie@mit.edu
mariali@mit.edu
eyf@mit.edu
bridgetl@mit.edu
armen@sloan.mit.edu
tatianav@mit.edu
lilyou@mit.edu
dierus@mit.edu
ckokesh@mit.edu
auds@mit.edu
grigt@mit.edu
siliangl@mit.edu
kemily@mit.edu
rileyis@mit.edu
rmoswane@mit.edu
gloriazh@mit.edu
ayjia@mit.edu
chriswu@mit.edu
andiliu@mit.edu
califyn@mit.edu
jhe2155@mit.edu
ashley22@mit.edu
raymondl@mit.edu
camim@mit.edu
raytran@mit.edu
shinghos@mit.edu
seperry@mit.edu
ayjchen@mit.edu
klpan@mit.edu
laiwachu@mit.edu
klpan@mit.edu
ayjchen@mit.edu
claraxu@mit.edu
ckf@mit.edu
asu@mit.edu
greerj@mit.edu
iliao@mit.edu
rasvani@mit.edu
kondylis@mit.edu
ruthluvu@mit.edu
ajsnyder@mit.edu
ekramer1@mit.edu
wayzhao@mit.edu
ebazakas@mit.edu
maximna@mit.edu
chuang26@mit.edu
karguo@mit.edu
ikrosado@mit.edu
audcui@mit.edu
wszeto@mit.edu
wangcx@mit.edu
mzw@mit.edu
jennyz@mit.edu
ctrlz@mit.edu
mgeo@mit.edu avelez9@mit.edu
sogreen@mit.edu
ylanaxu@mit.edu
isazeng@mit.edu
michesba@mit.edu
yujing6@mit.edu
mohamedm@mit.edu
curtiss@mit.edi
brianshi@mit.edu
meganlim@mit.edu
jocelin@mit.edu
mmsun@mit.edu
diao@mit.edu
janicey@mit.edu
mariali@mit.edu
timmyd@mit.edu
cfalor@mit.edu
imhari@mit.edu
sanjayra@mit.edu
durresi@mit.edu
rachanam@mit.edu
yimingz@mit.edu
fjiahai@mit.edu
danielxu@mit.edu
timberc@mit.edu
mtala@mit.edu
rld@mit.edu
haunz@mit.edu
gkim17@mit.edu
emfang@mit.edu
jhoule@mit.edu
duesselc@mit.edu
zawadx@mit.edu
michmo@mit.edu
nrwang@mit.edu
liviasyz@mit.edu
gytian@mit.edu
lianexu@mit.edu
lmtorola@mit.edu
hopefu@mit.edu
sgabbita@mit.edu
ramirjos@mit.edu
yimingc@mit.edu
zhixingc@mit.edu
erinliu@mit.edu
whuang03@mit.edu
guest@mit.edu
kaitlim@mit.edu
valmg@mit.edu
emmashi@mit.edu
evag@mit.edu
wangy872@mit.edu
isaq@mit.edu
alwinfy@mit.edu
iliu@mit.edu
asahteck@mit.edu
zanderh@mit.edu
mniwheat@mit.edu
msmyk@mit.edu
gyalpo@mit.edu
gracesun@mit.edu
cassye@mit.edu
jeslam@mit.edu
auds@mit.edu
angzhou@mit.edu
sabi@mit.edu
jih@mit.edu
kduan@mit.edu
rumilee@mit.edu and matildas@mit.edu
mlchiang@mit.edu
eileen03@mit.edu
mys1@mit.edu
yanswu@mit.edu
exliu@mit.edu
sophia_s@mit.edu
sophia_s@mit.edu
exliu@mit.edu
celinaz@mit.edu
mayajyo@mit.edu
seanjli@mit.edu
katchoi@mit.edu
henryrh@mit.edu
harryh@mit.edu
livlee@mit.edu
elizke@mit.edu
mehek@mit.edu
tahmid@mit.edu
samirdr@mit.edu
cadenm@mit.edu
hartleym@mit.edu
n10nyiam@mit.edu
mqwang@mit.edu
mshafim@mit.edu
dyanez@mit.edu
valmg@mit.edu
kaitlim@mit.edu
sncn@mit.edu
jyuan24@mit.edu
leelaf@mit.edu
yongao@mit.edu
yuecli@mit.edu
mtang17@mit.edu
fukumoto@mit.edu
eliu24@mit.edu
soche@mit.edu
abrenner@mit.edu
ckokesh@mit.edu
fatemaz@mit.edu
sklin@mit.edu
sabchen@mit.edu
pdeepu@mit.edu
fey@mit.edu
oop! elizabethli@college.harvard.edu
emilych@mit.edu
jessding@mit.edu
mnocito@mit.edu
jasonehc@mit.edu
eseeyave@mit.edu
hpropson@mit.edu
tingyilu@mit.edu
sarahgao@mit.edu
yazana@mit.edu
elibell@mit.edu
hmturner@mit.edu
amandali@mit.edu
timberc@mit.edu
mtala@mit.edu
mzw@mit.edu
ptimil@mit.edu
kuze@mit.edu
aliciaz@mit.edu
arushim@mit.edu
shinghos@mit.edu
sanupam@mit.edu
saniya@mit.edu
shrika@mit.edu
ajsnyder@mit.edu
ekramer1@mit.edu
henryrh@mit.edu
jianmc@mit.edu
dyanez@mit.edu
mshafim@mit.edu
cnamuroy@mit.edu
ashtofen@mit.edu
gting@mit.edu
bhliu@mit.edu zhengr@mit.edu
meganlim@mit.edu
joym@mit.edu
mtang17@mit.edu
hickling@mit.edu afh@mit.edu
mnatalie@mit.edu
assos@mit.edu
eileenp@mit.edu
keiran@mit.edu
stutik@mit.edu
notadib@mit.edu
auds@mit.edu
jeslam@mit.edu
mqwang@mit.edu
supriya@mit.edu
jbsera@mit.edu
lgershon@mit.edu
escharf@mit.edu
andresb@mit.edu
ckokesh@mit.edu
fatemaz@mit.edu
mstok@mit.edu

In [ ]:
log_tracking['caseyf@mit.edu'].current_weight

8

In [ ]:
#df = pd.read_csv('mince_dec.csv')
from google.colab import files
uploaded = files.upload()

df = pd.read_csv('entropy.csv')

high_weight_cutoff = 7

def parse_kerbs_str(kerbs_str):
  if pd.isna(kerbs_str):
      return []
  kerbs_str = str(kerbs_str)

  kerbs = re.split('[;,]', kerbs_str)

  out = []
  for kerb in kerbs:
      kerb = kerb.lower().strip()
      if not kerb:
        continue
      if not (kerb.endswith('@mit.edu') or '@' in kerb) :
          kerb += '@mit.edu'
      out.append(kerb)
  return out

def process_kerbs(kerbs_str):
    kerbs = parse_kerbs_str(kerbs_str) # Calls the parse_kerbs_str defined above

    weights = []
    is_pref = True
    for kerb in kerbs:
        if kerb not in log_tracking:
          weights.append(1)
          continue
        weights.append(log_tracking[kerb].current_weight)
        if log_tracking[kerb].last_attended is not None:
          is_pref = False

    # Avoid ZeroDivisionError if weights list is empty
    avg_weight = sum(weights) / len(weights) if weights else 0

    # is_pref = any(w >= high_weight_cutoff for w in weights)

    return ','.join(kerbs), ','.join(map(str, weights)), (avg_weight, int(is_pref))

def update_row(row):
    # Create a new dictionary from the row to ensure modifications don't interfere with original df
    new_data = row.to_dict()

    kerbs_str_processed, weight_str_processed, rest = process_kerbs(row['kerbs'])

    avg_weight, pref = rest

    new_data['kerbs'] = kerbs_str_processed
    new_data['weights'] = weight_str_processed
    new_data['avg_weight'] = avg_weight
    new_data['pref'] = pref

    # Return a new Series for df.apply to properly construct the updated DataFrame
    return pd.Series(new_data)

df = df.apply(update_row, axis=1)
df

Saving entropy.csv to entropy (2).csv

,seats,names,kerbs,allergies,weights,avg_weight,pref
0,2,Calista Huang,calistah@mit.edu,No,4,4.0,1
1,1,Nicole Zheng,nmzheng@mit.edu,No,2,2.0,1
2,1,Isabella Wu,isawu888@mit.edu,No,1,1.0,1
3,1,Sydney Saenz,saenz728@mit.edu,No,3,3.0,1
4,1,Akpandu Ekezie,akpandu@mit.edu,No,1,1.0,1
...,...,...,...,...,...,...,...
767,2,"Lindsay Reyes, Jessie Lin","linmari4@mit.edu,jessjlin@mit.edu",No,"5,1",3.0,0
768,2,"Bill Chen, Anna Gluschuk","runxi@mit.edu,annag26@mit.edu",No,"1,1",1.0,1
769,1,Emily Wong,emilywg@mit.edu,No,1,1.0,0
770,2,"Tiki Wu, Joyce Liu","twu@mit.edu,jliu07@mit.edu",No,"2,2",2.0,1
771,1,Isabelle Chan,iychan25@mit.edu,No,1,1.0,1

In [ ]:

pref_df, normal_df = df[df['pref'] == 1], df[df['pref'] != 1]

# Handle cases where avg_weight might be zero for sampling
# Add a small epsilon to zero weights to make them positive for the sample function
pref_df['sampling_weight'] = pref_df['avg_weight'].apply(lambda x: x if x > 0 else 0.001)
normal_df['sampling_weight'] = normal_df['avg_weight'].apply(lambda x: x if x > 0 else 0.001)

pref_df = pref_df.sample(frac=1, weights = pref_df['sampling_weight'], random_state=42) # Weight and shuffle prefs
lottery_df = normal_df.sample(frac=1, weights=normal_df['sampling_weight'], random_state=42) # Weight and shuffle normal
final_df = pd.concat([pref_df, lottery_df]).reset_index(drop=True)
final_df

/tmp/ipykernel_534/3470849919.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pref_df['sampling_weight'] = pref_df['avg_weight'].apply(lambda x: x if x > 0 else 0.001)
/tmp/ipykernel_534/3470849919.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  normal_df['sampling_weight'] = normal_df['avg_weight'].apply(lambda x: x if x > 0 else 0.001)

,seats,names,kerbs,allergies,weights,avg_weight,pref,sampling_weight
0,1,Peter Berggren,pmberg@mit.edu,No,4,4.0,1,4.000
1,2,"Megan Tian, Kayla Truong","megant@mit.edu,ktruong4@mit.edu",No,"7,1",4.0,1,4.000
2,2,"Melody Yu, Jason Youm","yumelody@mit.edu,jyoum@mit.edu",No,"2,2",2.0,1,2.000
3,2,"Louisa Zhu, Francis Liu","looeysa@mit.edu,fliu5@mit.edu",No,"3,1",2.0,1,2.000
4,1,Vernon Lin,vsl@mit.edu,No,3,3.0,1,3.000
...,...,...,...,...,...,...,...,...
767,2,"Hager Gomaa, Vaibhavi Addala","hagerg57@mit.edu,vaddala7@mit.edu",No,"0,0",0.0,0,0.001
768,1,Arielsie Li,arielsie@mit.edu,No,0,0.0,0,0.001
769,2,"Angela Wu, Yaqi Li","aywu@mit.edu,yaqili@mit.edu",No,"0,0",0.0,0,0.001
770,2,"Michelle Mo, Ellie Lei","michmo@mit.edu,ellei89@mit.edu",No,"0,0",0.0,0,0.001
771,1,Arielsie Li,arielsie@mit.edu,No,0,0.0,0,0.001

In [ ]:
expanded_rows = []

for _, row in final_df.iterrows():
    names = [n.strip() for n in str(row['names']).split(',')]
    kerbs = [k.strip() for k in str(row['kerbs']).split(',')]
    weights = [w.strip() for w in str(row['weights']).split(',')] if pd.notnull(row['weights']) else ["" for _ in kerbs]

    for i in range(len(names)):
        entry = {
            'seats': row['seats'] if i == 0 else '',
            'name': names[i] if i < len(names) else '',
            'kerb': kerbs[i] if i < len(kerbs) else '',
            'weight': weights[i] if i < len(weights) else '',
            'avg_weight': row['avg_weight'],
            'allergies': row['allergies'],
            'pref': row['pref'],
            'last_attended': log_tracking[kerbs[i]].last_attended if (i < len(kerbs) and kerbs[i] in log_tracking) else None
        }
        expanded_rows.append(entry)

expanded_df = pd.DataFrame(expanded_rows)
expanded_df.to_csv('winners.csv')
expanded_df

,seats,name,kerb,weight,avg_weight,allergies,pref,last_attended
0,1,Joy Ren,joyren@mit.edu,2,2.0,No,1,None
1,1,Ansia Sae,ansia@mit.edu,1,1.0,No,1,None
2,1,Alyssa Garger,alyssabg@mit.edu,1,1.0,allergic to hazelnuts,1,None
3,2,Angeline Peng,pengs14@mit.edu,8,5.0,No,1,None
4,,Mohamed Wacyl Meddour,meddour@mit.edu,2,5.0,No,1,None
...,...,...,...,...,...,...,...,...
339,1,Siyoung Kim,ksiyoung@mit.edu,1,1.0,No,0,lny
340,2,Alina Yang,alinay@mit.edu,1,1.0,No,0,swotw
341,,Yina Wang,yina1123@mit.edu,1,1.0,No,0,None
342,2,Hasan Zeki Yildiz,hzyildiz@mit.edu,1,1.0,No,0,swotw
343,,Cathy Hu,cathyhu3@mit.edu,1,1.0,No,0,None